export interface Review {
  id: string;
  userName: string;
  avatar: string;
  date: string;
  rating: number;
  city: string;
  tourName: string;
  tourId: string;
  reviewText: string;
  helpfulCount: number;
  hasImage?: boolean;
  imageUrl?: string;
}

export const reviews = [
  {
    id: '1',
    userName: 'على',
    date: '28/11/2024',
    rating: 5,
    city: 'makkah',
    tourName: 'تجربة إثرائية داخل المسجد الحرام',
    tourId: 88,
    tourType: "haram",
    reviewText: 'جولة المسجد الحرام كانت تجربة إثرائية بكل تفاصيلها! المرشد المرافق كان رائع، والصور التاريخية خلتنا نعيش الماضي لحظة بلحظة، وأجمل شيء كانت شهادة الزيارة في النهاية.',
    helpfulCount: 64,
  },
  {
    id: '2',
    userName: 'تميم',
    date: '15/12/2024',
    rating: 4,
    city: 'makkah',
    tourName: 'تجربة إثرائية داخل المسجد الحرام',
    tourId: 88,
    tourType: "haram",
    reviewText: 'جولة المسجد الحرام كانت مختلفة ، واستمتعت بالمعلومات التي قدمها المرشد المرافق ، الصور القديمة كانت تبهرنا في كل محطة، والأسئلة كانت تخلينا نشارك ونفكر.',
    helpfulCount: 22,
  },
  {
    id: '3',
    userName: 'سفيان',
    date: '10/11/2024',
    rating: 5,
    city: 'makkah',
    tourName: 'تجربة إثرائية داخل المسجد الحرام',
    tourId: 88,
    tourType: "haram",
    reviewText: 'جمعت بين المتعة والمعرفة، المرشد المرافق شرح القصص بأسلوب جميل، واللغة كانت واضحة ومفهومة، أما الصور التاريخية فقدمت لنا مشاهد ما كنا نعرفها من قبل، وختمنا بشهادة نفتخر فيها.',
    helpfulCount: 89,
  },
  {
    id: '4',
    userName: 'نعيمة',
    date: '05/12/2024',
    rating: 5,
    city: 'makkah',
    tourName: 'تجربة إثرائية داخل المسجد الحرام',
    tourId: 88,
    tourType: "haram",
    reviewText: 'الجولة كانت ممتعة ، كل شيء منظم ، القصص ممتعة ، تجربة فعلاً عصرية بتقنيات حديثة.',
    helpfulCount: 41,
  },
  {
    id: '5',
    userName: 'جاسم الباكر',
    date: '20/11/2024',
    rating: 4,
    city: 'makkah',
    tourName: 'تجربة إثرائية داخل المسجد الحرام',
    tourId: 88,
    tourType: "haram",
    reviewText: 'أجمل ما في الجولة التفاصيل الصغيرة. والأسئلة اللي تثير الفضول ، كل لحظة كانت شيقة بحد ذاتها',
    helpfulCount: 15,
  },
  {
    id: '6',
    userName: 'يونس حلوان',
    date: '12/12/2024',
    rating: 5,
    city: 'makkah',
    tourName: 'تجربة إثرائية داخل المسجد الحرام',
    tourId: 88,
    tourType: "haram",
    reviewText: 'جولة المسجد الحرام كانت جميلة ومليئة بالمعلومات الجديدة! الصور القديمة نقلتنا إلى الماضي، والأسئلة التفاعلية خلتنا ننتبه للتفاصيل أكثر',
    helpfulCount: 73,
  },
  {
    id: '7',
    userName: 'محمد سمير',
    date: '01/12/2024',
    rating: 4,
    city: 'makkah',
    tourName: 'تجربة إثرائية داخل المسجد الحرام',
    tourId: 88,
    tourType: "haram",
    reviewText: 'رحلة لا تُنسى مع لمسة تقنية حديثة. المرشد المرافق المثقف، وصور توثّق التاريخ، وأسئلة تخليك تفكر، وشهادة زيارة تذكرك دومًا بروعة التجربة.',
    helpfulCount: 56,
  },



  {
    id: '8',
    userName: 'عبد العزيز',
    date: '12/01/2025',
    rating: 5,
    city: 'madinah',
    tourName: 'تجربة إثرائية داخل المسجد النبوي',
    tourId: 87,
    tourType: "haram",
    reviewText: 'تجربة روحانية لا تُنسى في المسجد النبوي! المرشد المرافق أضاف عمقًا خاصًا للزيارة، والصور التاريخية ، والأسئلة التفاعلية كانت ممتعة جدًا، أما شهادة الزيارة فكانت لمسة جميلة في النهاية.',
    helpfulCount: 42,
  },
  {
    id: '9',
    userName: 'طاهر بلوتش',
    date: '15/01/2025',
    rating: 4,
    city: 'madinah',
    tourName: 'تجربة إثرائية داخل المسجد النبوي',
    tourId: 87,
    tourType: "haram",
    reviewText: 'جولة فوق التوقعات!استمعنا للقصص بلغتنا، وشاهدنا صورًا نادرة من تاريخ المسجد النبوي، وتفاعلنا مع الأسئلة اللي زادت متعة الجولة، وأجمل ختام كان استلام شهادة الزيارة',
    helpfulCount: 18,
  },
  {
    id: '10',
    userName: 'محمود حمزة',
    date: '22/02/2025',
    rating: 5,
    city: 'madinah',
    tourName: 'تجربة إثرائية داخل المسجد النبوي',
    tourId: 87,
    tourType: "haram",
    reviewText: 'تجربة إثرائية حديثة بروح الماضي!استمتعنا بشرح واضح من المرشد المرافق ، والأسئلة التفاعلية خلت الرحلة تعليمية ومسلية في نفس الوقت ، لن تكون الرحلة الأخيرة مع مزار',
    helpfulCount: 67,
  },
  {
    id: '11',
    userName: 'روهين زيب',
    date: '03/03/2025',
    rating: 5,
    city: 'madinah',
    tourName: 'تجربة إثرائية داخل المسجد النبوي',
    tourId: 87,
    tourType: "haram",
    reviewText: 'رحلة مليئة بالمشاعر والمعرفة 🕌،المرشد المرافق روى لنا القصص بأسلوب مؤثر، والصور التاريخية عرّفتنا على تفاصيل ما كنا نعرفها، والأسئلة الصغيرة خلتنا نعيش التجربة بكل حواسنا.',
    helpfulCount: 89,
  },
  {
    id: '12',
    userName: 'إقبال سراف',
    date: '10/03/2025',
    rating: 4,
    city: 'madinah',
    tourName: 'تجربة إثرائية داخل المسجد النبوي',
    tourId: 87,
    tourType: "haram",
    reviewText: 'المرشد المرافق غيّر تجربتي تمامًا.كنت زرت المسجد النبوي من قبل، لكن مع القصص والصور التاريخية، أحسست وكأني أزوره لأول مرة، وشهادة الزيارة كانت مفاجأة جميلة.',
    helpfulCount: 31,
  },
  {
    id: '13',
    userName: 'ابراهيم ابا',
    date: '18/04/2025',
    rating: 5,
    city: 'madinah',
    tourName: 'تجربة إثرائية داخل المسجد النبوي',
    tourId: 87,
    tourType: "haram",
    reviewText: 'جولة تجمع بين التقنية والإثراء. بين القصص التي تُروي،و الصور التاريخية التي تُعرض، والأسئلة التي تثير الفضول ، تجربة متكاملة تعيشك روح المكان، شكرًا مزار',
    helpfulCount: 52,
  },
  {
    id: '14',
    userName: 'عبد الرحيم علي',
    date: '05/05/2025',
    rating: 4,
    city: 'madinah',
    tourName: 'تجربة إثرائية داخل المسجد النبوي',
    tourId: 87,
    tourType: "haram",
    reviewText: 'استمتعنا بكل لحظة في المسجد النبوي. القصص التي رواها المرشد المرافق، الصور القديمة اللي تحكي تاريخ المكان، والأسئلة اللي تخليك تلاحظ التفاصيل أكثر ، كلها خلت التجربة لا تُنسى.',
    helpfulCount: 27,
  },
  {
    id: '15',
    userName: 'منار سيد',
    date: '12/05/2025',
    rating: 5,
    city: 'madinah',
    tourName: 'تجربة إثرائية داخل المسجد النبوي',
    tourId: 87,
    tourType: "haram",
    reviewText: 'رحلة للمسجد النبوي مليئة بالإلهام والمعرفة. كل تفصيل في الجولة كان محسوب : القصص، الصور، الأسئلة، وحتى شهادة الزيارة في النهاية كانت تذكّرنا بعظمة التجربة.',
    helpfulCount: 94,
  },
  {
    id: '16',
    userName: 'عائشه الجابري',
    date: '20/06/2025',
    rating: 5,
    city: 'madinah',
    tourName: 'تجربة إثرائية داخل المسجد النبوي',
    tourId: 87,
    tourType: "haram",
    reviewText: 'من أجمل التجارب اللي خضتها في المدينة المنورة. التطبيق منظم جدًا، والمرشد المرافق يرافقك خطوة بخطوة، والصور التاريخية تعيدك إلى البدايات، وشهادة الزيارة كانت تذكار رائع.',
    helpfulCount: 61,
  },

  {
    id: '17',
    userName: 'عبدالباسط طاهر',
    date: '10/01/2025',
    rating: 5,
    city: 'makkah',
    tourName: 'تجربة زيارة معالم مكة في رحلة تشاركية',
    tourId: 96,
    tourType: "bus",
    reviewText: 'الباص مريح ومكيّف، والتنظيم رائع من أول الحجز عبر التطبيق إلى آخر لحظة. أكثر ما شدّنا هو المرشد الصوتي اللي خلانا نعيش القصص أثناء زيارتنا لبئر طوى ومسجد الجن. تجربة روحانية وممتعة في آن واحد.',
    helpfulCount: 45,
  },
  {
    id: '18',
    userName: 'محمد نور',
    date: '22/01/2025',
    rating: 4,
    city: 'makkah',
    tourName: 'تجربة زيارة معالم مكة في رحلة تشاركية',
    tourId: 96,
    tourType: "bus",
    reviewText: 'من بداية الرحلة شعرنا بالراحة، والمرشد الصوتي زاد التجربة عمقًا. أحببنا كيف شرح تاريخ مسجد البيعة وجبل الرحمة بطريقة مؤثرة وسلسة.',
    helpfulCount: 12,
  },
  {
    id: '19',
    userName: 'عامر الطاف',
    date: '05/02/2025',
    rating: 5,
    city: 'makkah',
    tourName: 'تجربة زيارة معالم مكة في رحلة تشاركية',
    tourId: 96,
    tourType: "bus",
    reviewText: 'تجربة الواقع المعزز كانت مدهشة! مجرد ما وجّهنا الكاميرا على المعلم، ظهرت القصص أمامنا بطريقة تفاعلية رائعة، خصوصًا عند زيارة القصور الملكية وحي حراء الثقافي.',
    helpfulCount: 78,
  },
  {
    id: '20',
    userName: 'ابراهيم ايت لمعلم',
    date: '14/02/2025',
    rating: 5,
    city: 'makkah',
    tourName: 'تجربة زيارة معالم مكة في رحلة تشاركية',
    tourId: 96,
    tourType: "bus",
    reviewText: 'جميل كيف مزار جمع التقنية الحديثة مع الإرث الإسلامي. شفنا معالم مثل بئر طوى ومسجد البيعة، وسمعنا القصص الصوتية الموثّقة اللي خلتنا نعيش الحدث. نشكر مزار على هذه التجربة الممتعة',
    helpfulCount: 34,
  },
  {
    id: '21',
    userName: 'محمد أمين',
    date: '03/03/2025',
    rating: 4,
    city: 'makkah',
    tourName: 'تجربة زيارة معالم مكة في رحلة تشاركية',
    tourId: 96,
    tourType: "bus",
    reviewText: 'من حجز الرحلة عبر تطبيق مزار إلى ركوب الباص، كل شيء منظم ومريح. الجولة كانت مليئة بالمعلومات والقصص المؤثرة، خاصة عند زيارة جبل الرحمة.',
    helpfulCount: 21,
  },
  {
    id: '22',
    userName: 'حامد حسين',
    date: '19/03/2025',
    rating: 5,
    city: 'makkah',
    tourName: 'تجربة زيارة معالم مكة في رحلة تشاركية',
    tourId: 96,
    tourType: "bus",
    reviewText: 'الباص المكيّف والمرشد الصوتي خلّى الأطفال يستمتعوا بالرحلة، والواقع المعزز كان مثير جدًا لهم. استمتعنا بجمال حي حراء الثقافي وتاريخ الأماكن اللي زرناها. أنصح بهذه الجولة للعائلات',
    helpfulCount: 92,
  },
  {
    id: '23',
    userName: 'احمد محمود جمعه',
    date: '07/04/2025',
    rating: 4,
    city: 'makkah',
    tourName: 'تجربة زيارة معالم مكة في رحلة تشاركية',
    tourId: 96,
    tourType: "bus",
    reviewText: 'تنظيم، راحة، ومحتوى غني بالمعلومات. أعجبني أن كل معلم يرافقه قصة موثّقة وصور تاريخية، من مسجد الجن حتى جبل الرحمة. تجربة متكاملة ومبتكرة.',
    helpfulCount: 56,
  },
  {
    id: '24',
    userName: 'ريحانه تيلا',
    date: '25/04/2025',
    rating: 5,
    city: 'makkah',
    tourName: 'تجربة زيارة معالم مكة في رحلة تشاركية',
    tourId: 96,
    tourType: "bus",
    reviewText: 'لم أشعر أني في جولة تقليدية، بل في رحلة تفاعلية تجمع بين العلم والتأمل. الصوت، الصور، وحتى التقنيات الجديدة خلت كل محطة لها طابعها الخاص.',
    helpfulCount: 48,
  },
  {
    id: '25',
    userName: 'فيصل الاحمد',
    date: '12/05/2025',
    rating: 4,
    city: 'makkah',
    tourName: 'تجربة زيارة معالم مكة في رحلة تشاركية',
    tourId: 96,
    tourType: "bus",
    reviewText: 'الباصات نظيفة ومريحة جدًا، والمرشد الصوتي دقيق في المعلومة وهادئ في الطرح. استمتعنا كثيرًا عند زيارة القصور الملكية وسماع القصص حول تاريخها.',
    helpfulCount: 15,
  },
  {
    id: '26',
    userName: 'محمد حسن',
    date: '30/05/2025',
    rating: 5,
    city: 'makkah',
    tourName: 'تجربة زيارة معالم مكة في رحلة تشاركية',
    tourId: 96,
    tourType: "bus",
    reviewText: 'من أول ما بدأنا الرحلة من بئر طوى إلى حي حراء، شعرنا أننا نعيش تجربة تجمع الماضي بالمستقبل. كل شيء منظم وسلس، والمرشد الصوتي أضفى روح خاصة للرحلة.',
    helpfulCount: 63,
  }


];

export const reviewsEn = [
  {
    id: '1',
    userName: 'Drame Samba',
    date: '10/01/2025',
    rating: 5,
    city: 'makkah',
    tourName: 'An Enrichment Experience Inside Al-Masjid Al-Haram',
    tourId: 88,
    tourType: "haram",
    reviewText: 'Every stop was immersive thanks to the tour guide ; Selecting my language was easy with the app’s instant translation feature, the historical images beautifully told the stories, and the interactive questions kept me interested the entire time.',
    helpfulCount: 72,
  },
  {
    id: '2',
    userName: 'Mr. Salah',
    date: '15/01/2025',
    rating: 4,
    city: 'makkah',
    tourName: 'An Enrichment Experience Inside Al-Masjid Al-Haram',
    tourId: 88,
    tourType: "haram",
    reviewText: 'I heartily recommend! It was memorable and instructive Masjid Haram Tour. i am sure it won’t be the last tour with Mzar',
    helpfulCount: 38,
  },
  {
    id: '3',
    userName: 'Olatunji Abdulgafar',
    date: '02/02/2025',
    rating: 5,
    city: 'makkah',
    tourName: 'An Enrichment Experience Inside Al-Masjid Al-Haram',
    tourId: 88,
    tourType: "haram",
    reviewText: 'What a cleverly planned Masjid Haram tour! The rare historical images were fascinating and the quiz questions made it both educational and enjoyable. It felt official because of the certificate.',
    helpfulCount: 91,
  },
  {
    id: '4',
    userName: 'Sham Mahmud',
    date: '18/02/2025',
    rating: 5,
    city: 'makkah',
    tourName: 'An Enrichment Experience Inside Al-Masjid Al-Haram',
    tourId: 88,
    tourType: "haram",
    reviewText: "I valued the app's multilingual translation,also The certificate is a sentimental memento, thanks Mzar for this amazing Masjid Haram tour ",
    helpfulCount: 54,
  },
  {
    id: '5',
    userName: 'fazan malik',
    date: '05/03/2025',
    rating: 4,
    city: 'makkah',
    tourName: 'An Enrichment Experience Inside Al-Masjid Al-Haram',
    tourId: 88,
    tourType: "haram",
    reviewText: 'I really enjoyed the technology-driven experience and thanks for the Visit Certificate.',
    helpfulCount: 29,
  },
  {
    id: '6',
    userName: 'amer albazaz',
    date: '12/03/2025',
    rating: 5,
    city: 'makkah',
    tourName: 'An Enrichment Experience Inside Al-Masjid Al-Haram',
    tourId: 88,
    tourType: "haram",
    reviewText: 'Very fulfilling Masjid Haram tour: the multilingual audio guide and carefully chosen historical images, everyhting was top notch',
    helpfulCount: 83,
  },
  {
    id: '7',
    userName: 'Raji jimoh',
    date: '25/03/2025',
    rating: 4,
    city: 'makkah',
    tourName: 'An Enrichment Experience Inside Al-Masjid Al-Haram',
    tourId: 88,
    tourType: "haram",
    reviewText: 'It was great from beginning to end: the Professional tour guide , look at the old pictures, respond to interactive questions, and get your certificate of visit. Truly modern and meaningful',
    helpfulCount: 47,
  },
  {
    id: '8',
    userName: 'Farisha Patel',
    date: '10/04/2025',
    rating: 5,
    city: 'makkah',
    tourName: 'An Enrichment Experience Inside Al-Masjid Al-Haram',
    tourId: 88,
    tourType: "haram",
    reviewText: 'This was more than just a tour ; the multingual tranlsation feature helped me feel connected, the gallery of historical images added depth, the interactive quizzes made it enjoyable, and the certificate was the cherry on top.',
    helpfulCount: 66,
  },

  {
    id: '9',
    userName: 'Arif Mirza',
    date: '14/01/2025',
    rating: 5,
    city: 'madinah',
    tourName: 'An Enriching Experience Inside Al-Masjid An-Nabawi',
    tourId: 87,
    tourType: "haram",
    reviewText: "My Masjid an-Nabawi tour was made much more meaningful by the Accompanied Tour Guide’s stories. The interactive questions kept us interested, the historical images brought the past to life, and receiving the visit certificate at the conclusion made me feel like I had accomplished something truly unique.",
    helpfulCount: 42,
  },
  {
    id: '10',
    userName: 'Ms. Myriam Grinah',
    date: '28/01/2025',
    rating: 4,
    city: 'madinah',
    tourName: 'An Enriching Experience Inside Al-Masjid An-Nabawi',
    tourId: 87,
    tourType: "haram",
    reviewText: 'the tour guide made every stop an exploration of Masjid an-Nabawi. The final certificate was a beautiful way to wrap things up.',
    helpfulCount: 15,
  },
  {
    id: '11',
    userName: 'Mr. Sulaiman Malaji',
    date: '05/02/2025',
    rating: 5,
    city: 'madinah',
    tourName: 'An Enriching Experience Inside Al-Masjid An-Nabawi',
    tourId: 87,
    tourType: "haram",
    reviewText: 'Our hearts were won over by the tour as soon as we walked into Masjid an-Nabawi. The historical images helped us visualize early Islamic history and the entertaining quiz questions made it engaging. Afterward, I loved the certificate!',
    helpfulCount: 88,
  },
  {
    id: '12',
    userName: 'Ms. Soad Itani',
    date: '12/02/2025',
    rating: 5,
    city: 'madinah',
    tourName: 'An Enriching Experience Inside Al-Masjid An-Nabawi',
    tourId: 87,
    tourType: "haram",
    reviewText: "Everything went really well: the instant translation feature on the app made sure we didn't miss anything, selecting our language was easy, it is not gonna be the last Tour with Mzar",
    helpfulCount: 31,
  },
  {
    id: '13',
    userName: 'Farookh Kupe',
    date: '20/03/2025',
    rating: 4,
    city: 'madinah',
    tourName: 'An Enriching Experience Inside Al-Masjid An-Nabawi',
    tourId: 87,
    tourType: "haram",
    reviewText: 'The breadth of experience at Masjid an-Nabawi was what most impressed us. We saw old photographs that surrounded each landmark , Suggested for anyone looking for more than a simple visit.',
    helpfulCount: 24,
  },
  {
    id: '14',
    userName: 'Zaheer laher',
    date: '02/04/2025',
    rating: 5,
    city: 'madinah',
    tourName: 'An Enriching Experience Inside Al-Masjid An-Nabawi',
    tourId: 87,
    tourType: "haram",
    reviewText: 'Despite my prior visits to Masjid an-Nabawi, this time was completely different thanks to the tour guide . The historical photos added layers of story, the interactive quiz was fun for the family, and the certificate at the end sealed the experience.',
    helpfulCount: 95,
  },
  {
    id: '15',
    userName: 'aneil ahmed',
    date: '15/04/2025',
    rating: 4,
    city: 'madinah',
    tourName: 'An Enriching Experience Inside Al-Masjid An-Nabawi',
    tourId: 87,
    tourType: "haram",
    reviewText: 'We are delighted that we selected this tour for Masjid an-Nabawi. The tour was enjoyable for people of all ages thanks to the interactive questions, and the Accompanied Tour Guid that covered every detail. An unanticipated benefit was the visitation certificate.',
    helpfulCount: 57,
  },
  {
    id: '16',
    userName: 'Adeel imtiaz',
    date: '10/05/2025',
    rating: 5,
    city: 'madinah',
    tourName: 'An Enriching Experience Inside Al-Masjid An-Nabawi',
    tourId: 87,
    tourType: "haram",
    reviewText: 'We knew this was unique tour at Masjid an-Nabawi. It was a journey we will never forget because of the tour guide’s stories, the interactive reflections, and the final certificate.',
    helpfulCount: 68,
  },
  {
    id: '17',
    userName: 'nerffous',
    date: '25/05/2025',
    rating: 5,
    city: 'madinah',
    tourName: 'An Enriching Experience Inside Al-Masjid An-Nabawi',
    tourId: 87,
    tourType: "haram",
    reviewText: 'Just amazing. We received a certificate of our visit after being led by a kind narrator, assisted by rare historical photographs, and engaged by interactive questions at Masjid an-Nabawi. A mind-and-soul-enriching experience.',
    helpfulCount: 79,
  },
  {
    id: '18',
    userName: 'latif',
    date: '10/06/2025',
    rating: 5,
    city: 'makkah',
    tourName: 'Shared Journey Experience to Explore Makkah’s Landmarks',
    tourId: 96,
    tourType: "bus",
    reviewText: 'A truly remarkable experience!The audio guide in our native tongue made the trip extremely interesting, and the air-conditioned bus was incredibly comfortable. It was amazing to see Tuwa Well and Al-Jin Mosque and hear their stories via the app. I heartily endorse this tour! ',
    helpfulCount: 45,
  },
  {
    id: '19',
    userName: 'Mr. Mohamed Lachhab',
    date: '15/06/2025',
    rating: 4,
    city: 'makkah',
    tourName: 'Shared Journey Experience to Explore Makkah’s Landmarks',
    tourId: 96,
    tourType: "bus",
    reviewText: 'We admired how well-planned everything was; augmented reality technology offered a fresh perspective on ancient locations like Mount Arafat and the Royal Palaces.',
    helpfulCount: 28,
  },
  {
    id: '20',
    userName: 'Dr. Munazaah Ebad',
    date: '22/07/2025',
    rating: 5,
    city: 'makkah',
    tourName: 'Shared Journey Experience to Explore Makkah’s Landmarks',
    tourId: 96,
    tourType: "bus",
    reviewText: 'It was amazing to see sacred sites like Al-Jin Mosque and Jabal Al-Rahmah while using AR to visualize their history. The verified content made everything feel authentic and meaningful.',
    helpfulCount: 81,
  },
  {
    id: '21',
    userName: 'Abrahim Bushra',
    date: '05/08/2025',
    rating: 5,
    city: 'makkah',
    tourName: 'Shared Journey Experience to Explore Makkah’s Landmarks',
    tourId: 96,
    tourType: "bus",
    reviewText: 'After selecting a time and opening the Mzar app, the entire tour was prepared. Everything went smoothly from Tuwa Well to the Hira Cultural Districts. What most impressed us about the stories was their historical accuracy.',
    helpfulCount: 37,
  },
  {
    id: '22',
    userName: 'Mr. Omar SAHRAOUI',
    date: '12/09/2025',
    rating: 4,
    city: 'makkah',
    tourName: 'Shared Journey Experience to Explore Makkah’s Landmarks',
    tourId: 96,
    tourType: "bus",
    reviewText: 'The audio guide in eight languages was what made the trip unforgettable, but the modern bus made the journey more comfortable. Particularly when visiting the Bay\'ah Mosque and Hira Cultural District, the historical and religious facts were presented in a beautiful manner.',
    helpfulCount: 19,
  },
  {
    id: '23',
    userName: 'Ms. Roma Khatun',
    date: '20/10/2025',
    rating: 5,
    city: 'makkah',
    tourName: 'Shared Journey Experience to Explore Makkah’s Landmarks',
    tourId: 96,
    tourType: "bus",
    reviewText: 'I saw familiar locations in a whole new way thanks to the combination of AR storytelling, rich narration, and contemporary buses. The visit to the Hira Cultural District was incredibly motivating.',
    helpfulCount: 64,
  },
  {
    id: '24',
    userName: 'rubella ahmed',
    date: '02/11/2025',
    rating: 4,
    city: 'makkah',
    tourName: 'Shared Journey Experience to Explore Makkah’s Landmarks',
    tourId: 96,
    tourType: "bus",
    reviewText: 'Immersion technology, cozy transportation, and profoundly spiritual narratives. Everything was carefully considered by the Mzar team, particularly the authenticated historical content that lends credibility.',
    helpfulCount: 52,
  },
];

export const cities = [
  { id: 'all', label: 'جميع المدن' },
  { id: 'makkah', label: 'مكة المكرمة' },
  { id: 'madinah', label: 'المدينة المنورة' },
];

export const citiesEn = [
  { id: 'all', label: 'All Cities' },
  { id: 'makkah', label: 'Makkah' },
  { id: 'madinah', label: 'Madinah' },
];

export const tourTypes = [
  { id: 'all', label: 'جميع الجولات' },
  { id: 'haram', label: "جولات الحرمين" },
  { id: 'bus', label: "حافلة الجولات الإثرائية" },
  // { id: 'enriching', label: "الرحلات الإثرائية" },
];

export const tourTypesEn = [
  { id: 'all', label: 'All Tours' },
  { id: 'haram', label: 'Haram Tours' },
  { id: 'bus', label: 'Enriching Bus Trips' },
  // { id: 'enriching', label: 'Enriching Trips' },
];

export const ratingFilters = [
  { id: 'all', label: 'جميع التقييمات', minRating: 0 },
  { id: '5-stars', label: '5 نجوم فقط', minRating: 5 },
  { id: '4-plus', label: '4 نجوم فأعلى', minRating: 4 },
  { id: '3-plus', label: '3 نجوم فأعلى', minRating: 3 },
];

export const ratingFiltersEn = [
  { id: 'all', label: 'All Ratings', minRating: 0 },
  { id: '5-stars', label: '5 Stars Only', minRating: 5 },
  { id: '4-plus', label: '4 Stars & Up', minRating: 4 },
  { id: '3-plus', label: '3 Stars & Up', minRating: 3 },
];

export const sortOptions = [
  { id: 'newest', label: 'الأحدث' },
  { id: 'highest', label: 'الأعلى تقييمًا' },
  { id: 'helpful', label: 'الأكثر فائدة' },
];

export const ratingBreakdown = [
  { stars: 5, percentage: 78, count: 936 },
  { stars: 4, percentage: 16, count: 192 },
  { stars: 3, percentage: 4, count: 48 },
  { stars: 2, percentage: 1, count: 12 },
  { stars: 1, percentage: 1, count: 12 },
];
